version: '3.8'

services:
  reddot-website:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your environment variables here
      # - GROQ_API_KEY=your_groq_api_key_here
      # - MONGODB_URI=your_mongodb_connection_string_here
      # - MONGODB_DB_NAME=reddot-website
      # - CONTACT_EMAIL=keerthijai909@gmail.com
    volumes:
      - ./public:/app/public
    restart: unless-stopped